openapi: 3.0.0
info:
  title: Company API
  version: 1.0.0
  description: API for managing companies and their locations

servers:
  - url: http://localhost:8000
    description: Local development server

paths:
  /api/companies/all:
    get:
      summary: Get all companies
      description: Returns a list of all companies
      responses:
        "200":
          description: A list of companies
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Data fetched successfully.
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Company"
        "503":
          description: Service unavailable
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Service unavailable. Companies data file not found

  /api/companies/{company_id}/:
    get:
      summary: Get company details
      description: Returns details of a specific company by company_id
      parameters:
        - name: company_id
          in: path
          required: true
          description: ID of the company
          schema:
            type: string
      responses:
        "200":
          description: Company details
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Data fetched successfully.
                  data:
                    $ref: "#/components/schemas/Company"
        "404":
          description: Company not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Company not found
        "503":
          description: Service unavailable
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Service unavailable. Companies data file not found

  /api/companies/locations/{company_id}:
    get:
      summary: Get locations by company
      description: Returns all locations for a specific company by company_id
      parameters:
        - name: company_id
          in: path
          required: true
          description: ID of the company
          schema:
            type: string
      responses:
        "200":
          description: Company locations
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Data fetched successfully.
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Location"
        "404":
          description: Company not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Company not found
        "503":
          description: Service unavailable
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Service unavailable. Locations data file not found

components:
  schemas:
    Company:
      type: object
      properties:
        company_id:
          type: string
          example: "1"
        name:
          type: string
          example: "TechNova Solutions"
        address:
          type: string
          example: "123 Innovation Drive, San Francisco, CA 94105"
        latitude:
          type: string
          example: "37.7749"
        longitude:
          type: string
          example: "-122.4194"
    Location:
      type: object
      properties:
        location_id:
          type: string
          example: "1"
        company_id:
          type: string
          example: "1"
        name:
          type: string
          example: "OceanView Main Port"
        address:
          type: string
          example: "789 Harbor Blvd, Miami, FL 33131"
        latitude:
          type: string
          example: "25.7617"
        longitude:
          type: string
          example: "-80.1918"